import { test } from 'node:test';
import assert from 'node:assert/strict';
import { hiddenSummary, inlineText, markdownFileName, quietMentions, reviewMarkdown } from '../public/markdown.js';
import { runReview } from '../lib/review.js';
import { fakeAi, savedReply } from './helpers.js';

const demoAi = () => fakeAi([savedReply('demo-ai-reply'), savedReply('demo-claims-reply')]);
const PASTED = `diff --git a/src/app.js b/src/app.js
--- a/src/app.js
+++ b/src/app.js
@@ -1,2 +1,3 @@
 const db = require('./db');
+const rows = db.query(\`SELECT * FROM users WHERE id = \${req.query.id}\`);
 module.exports = rows;
`;

test('the AI review becomes a GitHub task list, most severe first in each area', async () => {
  const review = await runReview({ sample: 'demo' }, { ai: demoAi() });
  const md = reviewMarkdown(review);
  const lines = md.split('\n');
  assert.equal(lines[0], '### Review checklist: Add order search (#1)');
  assert.equal(lines[2], '**4 files, +36 / -11.** 2 must fix, 3 worth asking and 2 good to know.');
  assert.deepEqual(lines.filter((l) => l.startsWith('#### ')), ['#### Security', '#### Tests', '#### Breaking changes', '#### Docs', '#### Performance']);
  const tasks = lines.filter((l) => l.startsWith('- [ ] '));
  assert.equal(tasks.length, 7);
  assert.equal(tasks[0], `- [ ] **Must fix: Search text goes straight into SQL** ([src/search.ts:15](https://github.com/manangoesagain/bookshop-demo/blob/${review.pr.headSha}/src/search.ts#L15))`);
  assert.ok(tasks.includes('- [ ] **Must fix: Code changed, but no tests did** (4 code files changed, 0 test files)'));
  assert.ok(tasks.some((t) => t.startsWith('- [ ] **Good to know: Search returns every matching order**') && t.endsWith('_(not confirmed)_')));
  assert.ok(lines.includes('  Anyone can type SQL into the search box and read or delete other people\'s orders.'));
  assert.ok(lines.some((l) => l.startsWith('  Fix: ')));
  assert.equal(lines.at(-2), '<sub>Generated by PR Review Checklist. 4 AI suggestions hidden: 3 couldn\'t be checked against the code, 1 rejected by the second check.</sub>');
  assert.equal(md.at(-1), '\n');
});

test('hidden suggestions are only counted, never listed', async () => {
  const review = await runReview({ sample: 'demo' }, { ai: demoAi() });
  const md = reviewMarkdown(review);
  for (const entry of review.hidden) assert.ok(!md.includes(entry.title), entry.title);
});

test('ticked items stay ticked in the copy', async () => {
  const review = await runReview({ sample: 'demo' }, { ai: demoAi() });
  const sql = review.areas[0].items[0];
  const md = reviewMarkdown(review, { done: new Set([sql.id]) });
  assert.match(md, /^- \[x\] \*\*Must fix: Search text goes straight into SQL\*\*/m);
  assert.equal(md.split('\n').filter((l) => l.startsWith('- [x] ')).length, 1);
});

test('a removed line links to the old file at the base commit', async () => {
  const review = await runReview({ sample: 'demo' }, { ai: demoAi() });
  const item = { ...review.areas[2].items[0], side: 'L', line: 41, link: `https://github.com/manangoesagain/bookshop-demo/blob/${review.pr.baseSha}/src/users.ts#L41` };
  const md = reviewMarkdown({ ...review, areas: [{ ...review.areas[2], items: [item] }], hidden: [] });
  assert.match(md, new RegExp(`\\(\\[src/users\\.ts:41\\]\\(https://github\\.com/manangoesagain/bookshop-demo/blob/${review.pr.baseSha}/src/users\\.ts#L41\\), a removed line\\)`));
});

test('a pasted diff has no links: plain file:line in code', async () => {
  const review = await runReview({ diff: PASTED });
  const md = reviewMarkdown(review);
  assert.match(md, /^### Review checklist: pasted diff$/m);
  assert.match(md, /\(`src\/app\.js:2`\)/);
  assert.ok(!md.includes('https://'));
  assert.equal(markdownFileName(review), 'review-pasted-diff.md');
});

test('basic mode and all-clear summaries say what wasn\'t checked or what looks good', async () => {
  const basic = reviewMarkdown(await runReview({ sample: 'demo' }));
  assert.match(basic, /\*\*4 files, \+36 \/ -11\.\*\* 2 must fix and 3 worth asking\./);
  assert.match(basic, /<sub>Generated by PR Review Checklist\.<\/sub>\n$/);
  const clear = reviewMarkdown(await runReview({ sample: 'clean' }, { ai: fakeAi(['{"items":[],"clear":["security","tests","breaking","docs","performance"]}']) }));
  assert.match(clear, /No problems found\. Security, tests, breaking changes, docs and performance look good\./);
  assert.ok(!clear.includes('- [ ]'));
});

test('code in backticks stays intact; pipes are left alone', () => {
  assert.equal(inlineText('Pass `q` as a parameter'), 'Pass `q` as a parameter');
  assert.equal(inlineText('Use `a || b` here | or there'), 'Use `a || b` here | or there');
  assert.equal(inlineText('``code with ` inside`` then `x`'), '``code with ` inside`` then `x`');
  assert.equal(inlineText('snake_case stays, user-id stays'), 'snake_case stays, user-id stays');
});

test('item text can\'t become HTML, links, emphasis, headings or mentions', () => {
  assert.equal(inlineText('<img src=x onerror=alert(1)>'), '\\<img src=x onerror=alert(1)>');
  assert.equal(inlineText('see [here](https://evil.example)'), 'see \\[here\\](https://evil.example)');
  assert.equal(inlineText('*bold* and _em_ and ~~gone~~'), '\\*bold\\* and \\_em\\_ and \\~\\~gone\\~\\~');
  assert.equal(inlineText('# Heading'), '\\# Heading');
  assert.equal(inlineText('- list'), '\\- list');
  assert.equal(inlineText('1. list'), '1\\. list');
  assert.equal(inlineText('thanks @octocat, see @app.route'), 'thanks `@octocat`, see `@app.route`');
  assert.equal(inlineText('mail me at me@example.com'), 'mail me at me@example.com');
  assert.equal(inlineText('a stray ` backtick'), 'a stray \\` backtick');
  assert.equal(inlineText('two\nlines'), 'two lines');
  assert.equal(inlineText('&copy; vs AT&T'), '&amp;copy; vs AT&T');
});

test('titles from a PR are escaped in the heading too', () => {
  const review = {
    pr: { title: '<b>Fix</b> [things]', number: 3, repo: 'a/b' },
    stats: { files: 1, additions: 1, deletions: 0 },
    areas: [{ id: 'security', name: 'Security', status: 'clear', items: [] }],
    hidden: [],
  };
  assert.match(reviewMarkdown(review), /^### Review checklist: \\<b>Fix\\<\/b> \\\[things\\\] \(#3\)$/m);
});

test('only github.com links are written, and parentheses can\'t end a link early', () => {
  const base = { area: 'security', severity: 'must-fix', title: 'T', file: 'src/a (copy).ts', side: 'R', line: 2, why: '', fix: '', origin: 'hint' };
  const review = (link) => ({
    pr: { title: 'x', number: 1, repo: 'a/b' },
    stats: { files: 1, additions: 1, deletions: 0 },
    areas: [{ id: 'security', name: 'Security', status: 'issues', items: [{ ...base, link }] }],
    hidden: [],
  });
  assert.match(reviewMarkdown(review('https://github.com/a/b/blob/abc/src/a (copy).ts#L2')), /\(https:\/\/github\.com\/a\/b\/blob\/abc\/src\/a%20%28copy%29\.ts#L2\)/);
  assert.match(reviewMarkdown(review('javascript:alert(1)')), /\(`src\/a \(copy\)\.ts:2`\)/);
});

test('hidden summary and file names', () => {
  assert.equal(hiddenSummary([]), null);
  assert.equal(hiddenSummary([{ removedBy: 'limit' }]), '1 AI suggestion hidden: 1 over the limit');
  assert.equal(markdownFileName({ pr: { repo: 'manangoesagain/bookshop-demo', number: 1 } }), 'review-bookshop-demo-1.md');
  assert.equal(markdownFileName({ pr: { repo: '../../etc', number: 2 } }), 'review-etc-2.md');
});

test('Python names like __init__ stay as they are, not italics', () => {
  assert.equal(inlineText('Add a test for __init__ and _private'), 'Add a test for \\_\\_init\\_\\_ and \\_private');
  assert.equal(inlineText('snake_case stays readable'), 'snake_case stays readable');
});

test('a copied comment never notifies anyone it names', () => {
  assert.equal(quietMentions('cc @octocat and @org/security-team, please look'), 'cc `@octocat` and `@org/security-team`, please look');
  assert.equal(quietMentions('mail me at a@b.com'), 'mail me at a@b.com');
});
